[phases.setup]
nixPkgs = ["php84", "php84Extensions.sqlite3", "php84Extensions.pdo_sqlite", "php84Extensions.intl", "php84Extensions.zip", "php84Extensions.fileinfo", "php84Extensions.mbstring", "php84Extensions.openssl", "php84Extensions.dom", "php84Extensions.curl", "php84Extensions.session", "php84Extensions.tokenizer", "php84Extensions.xml"]
nixLibs = ["glibc"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip"]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
